port: ":8080"

middleware_config:
  auth_apikey:
    valid_keys:
      - "abc-123"
      - "dwe-659"

services:
  - name: "cart-inventory-service"
    route_pattern: "/api"
    urls:
      - "http://localhost:8081"
    middleware:
      - "correlation_id"
      - "rate_limit"
      - "metrics"
      - "auth_apikey"
    rate_limit_rps: 2
    rate_limit_burst: 3

  - name: "product-service"
    route_pattern: "/product"
    urls:
      - "http://localhost:8082"
    middleware:
      - "correlation_id"
      - "rate_limit"
      - "metrics"
      - "auth_apikey"
    rate_limit_rps: 2
    rate_limit_burst: 3

  - name: "order-service"
    route_pattern: "/order"
    urls:
      - "http://localhost:8083"
    middleware:
      - "correlation_id"
      - "rate_limit"
      - "metrics"
      - "auth_apikey"
    rate_limit_rps: 2
    rate_limit_burst: 3