FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go.mod and sum from the root
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /gateway ./gateway.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /

COPY --from=builder /gateway /gateway
COPY --from=builder /app/config.yaml /config.yaml

EXPOSE 8080
CMD ["/gateway"]